In [1]:
import torch
from torchvision import models
from torch import nn

In [4]:
resnet = models.resnet50(pretrained=True)
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [16]:
model = torch.nn.Sequential(*(list(resnet.children())[:-1]))
#print(model)
#emb = model.forward(torch.rand(1,3,244,244))
#print(emb.shape)
#emb.reshape(emb.shape[0],-1).size()
model

Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)


In [18]:
model[7][2]

Bottleneck(
  (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
)

In [36]:
mobile_net = models.mobilenet_v2(pretrained=True)

In [37]:

#mobile_net.classifier[1] = nn.Linear(1280,2,True)
x = mobile_net.features
e=x.forward(torch.rand(1,3,244,244))
e.shape

torch.Size([1, 1280, 8, 8])

In [45]:
mobile_net

MobileNetV2(
  (features): Sequential(
    (0): ConvBNReLU(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=Tr

In [46]:
mobile_net.classifier[1].in_features

1280

In [40]:
mobile_net.forward(torch.rand(1,3,244,244)).shape

torch.Size([1, 1000])

In [19]:
from model import fashion_model
from data import get_dataloader

In [23]:
dataloaders, classes, dataset_size = get_dataloader(debug=True, batch_size=1, num_workers=1)

In [20]:
classes = 2
model = fashion_model(classes)
print(model)

child  0  was frozen
child  1  was frozen
child  2  was frozen
child  3  was frozen
child  4  was frozen
child  5  was frozen
child  6  was frozen
child  7  was frozen
child  8  was frozen
child  9  was frozen
child  10  was frozen
child  11  was frozen
child  12  was frozen
child  13  was frozen
child  14  was frozen
child  15  was frozen
child  16  was not frozen
child  17  was not frozen
child  18  was not frozen
fashion_model(
  (model): Sequential(
    (0): ConvBNReLU(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace

In [8]:
if (5+1) not in [7,8,9]:
    print(1)

1


In [43]:
for input1, input2, labels in dataloaders['train']:
    r1 = input1
    r2 = input2
    label = labels
    break

In [44]:
r1.shape

torch.Size([1, 3, 224, 224])

In [59]:
model.eval()
output = model.forward(r1,r2)
output

tensor([[-0.0400, -0.2906]], grad_fn=<AddmmBackward>)

In [60]:
emb1 = model.model.forward(r1)
emb2 = model.model.forward(r2)
emb3 = nn.functional.adaptive_avg_pool2d(emb1, 1).reshape(emb1.shape[0], -1)
emb4 = nn.functional.adaptive_avg_pool2d(emb2, 1).reshape(emb2.shape[0], -1)

In [61]:
print(emb1.shape,emb2.shape,emb3.shape,emb4.shape)

torch.Size([1, 1280, 7, 7]) torch.Size([1, 1280, 7, 7]) torch.Size([1, 1280]) torch.Size([1, 1280])


In [62]:
emb = torch.cat((emb3,emb4),1)
emb.shape

torch.Size([1, 2560])

In [63]:
output = model.classifier(emb)
output

tensor([[-0.0400, -0.2906]], grad_fn=<AddmmBackward>)

In [18]:
m = nn.Sigmoid()
m(output)

tensor([[0.7875]], grad_fn=<SigmoidBackward>)

In [65]:
criterion = nn.CrossEntropyLoss(reduction='none')
criterion(output, labels)

tensor([0.8263], grad_fn=<NllLossBackward>)

In [92]:
import torch.nn.functional as F
x1 = torch.rand(2,3,224,224)
x2 = torch.rand(2,3,224,224)

tensor([[0.4904, 0.5096],
        [0.4865, 0.5135]], grad_fn=<SoftmaxBackward>)

In [95]:
output_ = model.forward(x1,x2)
F.softmax(output_,dim=1)

tensor([[0.4904, 0.5096],
        [0.4865, 0.5135]], grad_fn=<SoftmaxBackward>)

In [74]:
labels = torch.Tensor([0,1]).type(torch.int64)
labels

tensor([0, 1])

In [102]:
loss_init = criterion(output_,labels)
_, idxs = loss_init.topk(1) 

In [104]:
loss = torch.mean(loss_init.index_select(0, idxs))

In [106]:
model.train()
loss.backward()

In [116]:
torch.max(torch.Tensor([[121,32,55,33,67,21]]),1)

torch.return_types.max(
values=tensor([121.]),
indices=tensor([0]))

In [112]:
_, pred = torch.max(torch.Tensor([[121,32],[33,67]]),1)
print(pred)

tensor([0, 1])
